name: Coverage
on:
  pull_request:

jobs:
  coverage_update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Test
        run: bundle exec rspec
      - name: Simplecov Report
        uses: aki77/simplecov-report-action@v1
        with:
          token: ${{secrets.GITHUB_TOKEN}}
          failedThreshold: 2
