name: Coverage update
on:
  push:
    branches:
      - main
jobs:
  coverage_update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: devmasx/coverage-check-action@v1.0.0
        with:
          result_path: coverage/.last_run.json
          token: ${{secrets.GITHUB_TOKEN}}
          type: simplecov
          min_coverage: 90
