name: Symfony

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  symfony-tests:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: root
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
    #  To automatically get bug fixes and new Php versions for shivammathur/setup-php,
    # change this to (see https://github.com/shivammathur/setup-php#bookmark-versioning):
    # uses: shivammathur/setup-php@v2
    - uses: shivammathur/setup-php@v2
      with:
        php-version: '7.4'
    - uses: actions/checkout@v2
    - name: Copy .env.test.local
      run: php -r "file_exists('.env.test.local') || copy('.env.test', '.env.test.local');"
    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v2
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-
    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
    - name: Create Database
      env:
        DATABASE_URL: mysql://root:root@127.0.0.1:3306/testing?serverVersion=8.0&charset=utf8mb4
      run: |
        bin/console --env=test d:d:c --no-interaction
        bin/console --env=test d:m:m --no-interaction
        bin/console --env=test d:f:load --no-interaction
    - name: Execute tests (Unit and Feature tests) via PHPUnit
      run: vendor/bin/phpunit
    - name: Execute CodeSniffer tests
      run: vendor/bin/phpcs --standard=PSR12 --ignore=tests/bootstrap.php src tests
    - name: Execute PhpStan tests
      run: vendor/bin/phpstan analyse src tests
    - name: Coverage check
      uses: devmasx/coverage-check-action@v1.2.0
      with:
        type: lcov
        result_path: coverage/example.lcov
